const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
const traffic=$('#traffic'),trafficOut=$('#trafficOut'),keyword=$('#keyword'),keywordView=$('#keywordView'),flowState=$('#flowState');
function fmt(n){return Number(n).toLocaleString('en-KE')}
traffic.addEventListener('input',()=>{trafficOut.value=fmt(traffic.value);trafficOut.textContent=fmt(traffic.value);const q=Math.max(18.6,Math.min(28,18.6+((traffic.value-8400)/8400)*4));$('#heroRate').textContent=q.toFixed(1)+'%';});
keyword.addEventListener('input',()=>keywordView.textContent=(keyword.value||'EDIT').toUpperCase());
$$('.aud').forEach(b=>b.addEventListener('click',()=>{$$('.aud').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#leadName').textContent=b.textContent==='VIP'?'AMARA / VIP INTENT':b.textContent==='NEW'?'NIA / NEW INTENT':'MAYA / HIGH INTENT'}));
function pulseNode(node){node.classList.add('focus');setTimeout(()=>node.classList.remove('focus'),900)}
$$('.node-action').forEach((b,i)=>b.addEventListener('click',()=>{const node=b.closest('.flow-node');pulseNode(node);flowState.textContent=['CREATIVE OPENED','TRIGGER TESTED','SALES DESK READY'][i]||'HANDOFF READY';if(i===2)$('#desk').scrollIntoView({behavior:'smooth'})}));
function simulate(){flowState.textContent='RUNNING…';const nodes=$$('.flow-node');nodes.forEach(n=>n.classList.remove('focus'));nodes.forEach((n,i)=>setTimeout(()=>{pulseNode(n);if(i===nodes.length-1)flowState.textContent='SIMULATION COMPLETE';},i*380));$('#score').textContent='96';$('#qualified').textContent=fmt(Math.round(Number(traffic.value)*.052));}
$('#runDemo').addEventListener('click',simulate);$('#launch').addEventListener('click',simulate);
$$('.chat-actions button').forEach(btn=>btn.addEventListener('click',()=>{const body=$('#chatBody');const customer=document.createElement('div');customer.className='bubble customer';customer.textContent=btn.dataset.reply;body.appendChild(customer);setTimeout(()=>{const seller=document.createElement('div');seller.className='bubble seller';seller.textContent=btn.dataset.reply.includes('payment')?'Absolutely. I can send the secure payment options and hold your preferred piece while we confirm size.':btn.dataset.reply.includes('less formal')?'Absolutely — I’ll refine the shortlist toward polished but less formal options. Give me one moment. ✨':'Yes — I’ll confirm EU 38 availability and reserve it if it’s in stock. ✨';body.appendChild(seller);body.scrollTop=body.scrollHeight},550)}));
$('#openDesk').addEventListener('click',()=>$('#desk').scrollIntoView({behavior:'smooth'}));
$('#convert').addEventListener('click',e=>{e.currentTarget.innerHTML='CONVERTED <b>✓</b>';e.currentTarget.style.background='var(--sage)';e.currentTarget.style.color='var(--ink)';$('#saleRate').textContent='21.4%';$('#heroRate').textContent='21.4%';});
$('#handoff').addEventListener('click',e=>{e.currentTarget.textContent='HUMAN OWNER ASSIGNED ✓';e.currentTarget.style.borderColor='var(--blush)';});
$('#refreshMetrics').addEventListener('click',()=>{const q=Number($('#qualified').textContent.replace(/,/g,''));$('#qualified').textContent=fmt(q+Math.floor(Math.random()*19+4));$('#waStarts').textContent=231+Math.floor(Math.random()*12);$('#openRate').textContent=(74.8+Math.random()*2).toFixed(1)+'%';$('#refreshMetrics').textContent='SIGNALS REFRESHED ✓';setTimeout(()=>$('#refreshMetrics').textContent='↻ REFRESH SIGNALS',1400)});
$$('.touch').forEach(t=>t.addEventListener('click',()=>{$$('.touch').forEach(x=>x.classList.remove('active'));t.classList.add('active');const n=t.querySelector('b').textContent;$('#leadName').textContent=n==='WHATSAPP'?'MAYA / READY TO BUY':n==='QUALIFICATION'?'MAYA / QUALIFIED':'MAYA / HIGH INTENT'}));
trafficOut.value=fmt(traffic.value);