const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const traffic=$('#traffic'),trafficOut=$('#trafficOut'),keyword=$('#keyword'),keywordView=$('#keywordView'),flowState=$('#flowState');
const state={running:false,converted:false,handoff:false,creative:false,trigger:false};
function fmt(n){return Number(n).toLocaleString('en-KE')}
function setStatus(text){flowState.textContent=text}
function pulseNode(node){if(!node)return;node.classList.remove('focus');void node.offsetWidth;node.classList.add('focus');setTimeout(()=>node.classList.remove('focus'),900)}
function toast(message){let t=$('#appToast');if(!t){t=document.createElement('div');t.id='appToast';document.body.appendChild(t)}t.textContent=message;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2600)}
function modal(title,body,actions=''){let m=$('#appModal');if(!m){m=document.createElement('div');m.id='appModal';m.innerHTML='<div class="modal-backdrop"></div><div class="modal-card"><button class="modal-close" aria-label="Close">×</button><div class="modal-content"></div></div>';document.body.appendChild(m);m.querySelector('.modal-backdrop').onclick=()=>m.classList.remove('open');m.querySelector('.modal-close').onclick=()=>m.classList.remove('open')}m.querySelector('.modal-content').innerHTML=`<div class="modal-kicker">CONVERSION STUDIO</div><h3>${title}</h3><div class="modal-copy">${body}</div>${actions}`;m.classList.add('open');return m}
function updateFunnel(){const v=Number(traffic.value);const engaged=Math.round(v*.72),keywords=Math.round(v*.31),qualified=Math.round(v*.0457),converted=state.converted?Math.round(qualified*.214):Math.round(qualified*.186);const rows=$$('.funnel-row');if(rows[0])rows[0].querySelector('b').textContent=fmt(v);if(rows[1])rows[1].querySelector('b').textContent=fmt(engaged);if(rows[2])rows[2].querySelector('b').textContent=fmt(keywords);if(rows[3])rows[3].querySelector('b').textContent=fmt(qualified);if(rows[4])rows[4].querySelector('b').textContent=fmt(converted);$('#qualified').textContent=fmt(qualified);$('#waStarts').textContent=fmt(Math.round(v*.0275));$('#heroRate').textContent=(state.converted?21.4:Math.max(18.6,Math.min(28,18.6+((v-8400)/8400)*4))).toFixed(1)+'%'}
traffic.addEventListener('input',()=>{trafficOut.value=fmt(traffic.value);trafficOut.textContent=fmt(traffic.value);updateFunnel()});
keyword.addEventListener('input',()=>{keywordView.textContent=(keyword.value.trim()||'EDIT').toUpperCase()});
$$('.aud').forEach(b=>b.addEventListener('click',()=>{$$('.aud').forEach(x=>x.classList.remove('active'));b.classList.add('active');const type=b.textContent.trim();const names={VIP:'AMARA / VIP INTENT',NEW:'NIA / NEW INTENT',WARM:'MAYA / HIGH INTENT'};$('#leadName').textContent=names[type];$('#score').textContent=type==='VIP'?'98':type==='NEW'?'84':'92';toast(`${type} audience selected — lead context updated.`)}));
function runNode(node,index){return new Promise(resolve=>{setTimeout(()=>{pulseNode(node);resolve()},index*360)})}
async function simulate(){if(state.running)return;state.running=true;setStatus('RUNNING…');const nodes=$$('.flow-node');nodes.forEach(n=>n.classList.remove('focus'));for(let i=0;i<nodes.length;i++)await runNode(nodes[i],1);state.running=false;setStatus('SIMULATION COMPLETE');$('#score').textContent='96';updateFunnel();toast('Live simulation completed — the lead reached the WhatsApp Sales Desk.');$('#desk').scrollIntoView({behavior:'smooth',block:'start'})}
$('#runDemo').addEventListener('click',simulate);$('#launch').addEventListener('click',()=>{setStatus('CAMPAIGN LAUNCHING…');toast('Campaign launched in simulation mode.');simulate()});
const nodeMessages={
'VIEW CREATIVE':()=>modal('The Hook','<p><strong>REEL / 01</strong></p><p>“You don’t need another dress. You need the one they remember.”</p><div class="modal-data"><span>FORMAT<br><b>9:16 REEL</b></span><span>CTA<br><b>COMMENT: EDIT</b></span><span>OBJECTIVE<br><b>INTENT</b></span></div><button class="modal-primary" data-modal-action="creative">MARK CREATIVE READY ↗</button>'),
'TEST TRIGGER':()=>{state.trigger=true;keywordView.textContent=(keyword.value.trim()||'EDIT').toUpperCase();pulseNode($('.trigger'));setStatus('TRIGGER VERIFIED');toast(`Trigger verified: commenting “${keywordView.textContent}” routes the lead to the private edit.`);modal('Trigger Test','<p>The trigger is configured and responding in the demo flow.</p><div class="trigger-preview"><span>COMMENT</span><b>'+keywordView.textContent+'</b><i>→ PRIVATE DM</i></div><button class="modal-primary" data-modal-action="close">CONTINUE FLOW ↗</button>')},
'OPEN SALES DESK':()=>$('#desk').scrollIntoView({behavior:'smooth',block:'start'})};
$$('.node-action').forEach(b=>b.addEventListener('click',()=>{const label=b.textContent.replace('↗','').trim();const node=b.closest('.flow-node');pulseNode(node);setStatus(label==='VIEW CREATIVE'?'CREATIVE OPENED':label==='TEST TRIGGER'?'TRIGGER VERIFIED':'SALES DESK OPEN');if(nodeMessages[label])nodeMessages[label]()}));
$('#openDesk').addEventListener('click',()=>$('#desk').scrollIntoView({behavior:'smooth',block:'start'}));
$$('.chat-actions button').forEach(btn=>btn.addEventListener('click',()=>{const body=$('#chatBody');const customer=document.createElement('div');customer.className='bubble customer';customer.textContent=btn.dataset.reply;body.appendChild(customer);body.scrollTop=body.scrollHeight;setTimeout(()=>{const seller=document.createElement('div');seller.className='bubble seller';const r=btn.dataset.reply;seller.textContent=r.includes('payment')?'Absolutely. I can send the secure payment options and hold your preferred piece while we confirm size.':r.includes('less formal')?'Absolutely — I’ll refine the shortlist toward polished but less formal options. Give me one moment. ✨':'Yes — I’ll confirm EU 38 availability and reserve it if it’s in stock. ✨';body.appendChild(seller);body.scrollTop=body.scrollHeight;toast('Seller response added to the live conversation.')},550)}));
$('#convert').addEventListener('click',e=>{state.converted=true;e.currentTarget.innerHTML='CONVERTED <b>✓</b>';e.currentTarget.classList.add('is-done');$('#saleRate').textContent='21.4%';$('#heroRate').textContent='21.4%';updateFunnel();toast('Lead #00482 marked converted. Revenue signal updated.')});
$('#handoff').addEventListener('click',e=>{state.handoff=true;e.currentTarget.textContent='HUMAN OWNER ASSIGNED ✓';e.currentTarget.classList.add('is-done');toast('Lead handed off to Regina / Sales Desk. Automation is now paused for this lead.')});
$('#refreshMetrics').addEventListener('click',()=>{const q=Number($('#qualified').textContent.replace(/,/g,''));$('#qualified').textContent=fmt(q+Math.floor(Math.random()*19+4));$('#waStarts').textContent=fmt(231+Math.floor(Math.random()*12));$('#openRate').textContent=(74.8+Math.random()*2).toFixed(1)+'%';$('#refreshMetrics').textContent='SIGNALS REFRESHED ✓';toast('Revenue signals refreshed.');setTimeout(()=>$('#refreshMetrics').textContent='↻ REFRESH SIGNALS',1400)});
$$('.touch').forEach(t=>t.addEventListener('click',()=>{$$('.touch').forEach(x=>x.classList.remove('active'));t.classList.add('active');const n=t.querySelector('b').textContent;const map={WHATSAPP:['MAYA / READY TO BUY','98'],QUALIFICATION:['MAYA / QUALIFIED','96'],'PRIVATE DM':['MAYA / HIGH INTENT','94'],'COMMENT “EDIT”':['MAYA / HIGH INTENT','91'],'REEL VIEW':['MAYA / HIGH INTENT','88']};const v=map[n]||map['REEL VIEW'];$('#leadName').textContent=v[0];$('#score').textContent=v[1];toast(`${n} selected — lead signal board updated.`)}));
$$('.recommend div').forEach(item=>item.addEventListener('click',()=>{const name=item.querySelector('b')?.textContent||'Selected edit';const price=item.querySelector('span')?.textContent||'';modal(name,`<p>${price}</p><p>This recommendation is attached to the lead context and ready for a seller conversation.</p><button class="modal-primary" data-modal-action="send">SEND TO CUSTOMER ↗</button>`)}));
document.addEventListener('click',e=>{const action=e.target.closest('[data-modal-action]')?.dataset.modalAction;if(!action)return;const m=$('#appModal');if(action==='send'){const body=$('#chatBody');const seller=document.createElement('div');seller.className='bubble seller';seller.textContent='I’ve added that recommendation to your shortlist. ✨';body.appendChild(seller);body.scrollTop=body.scrollHeight;toast('Recommendation sent into the sales conversation.')}if(action==='creative'){state.creative=true;toast('Creative marked ready for launch.')}m?.classList.remove('open')});
$$('.topbar nav a').forEach(a=>a.addEventListener('click',()=>{const target=document.querySelector(a.getAttribute('href'));if(target)target.scrollIntoView({behavior:'smooth',block:'start'})}));
trafficOut.value=fmt(traffic.value);updateFunnel();